name: Hello World CI

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker $USER  # Add the current user to the docker group to run Docker without sudo
          newgrp docker  # Activate the changes to group membership

      - name: Build Docker Image
        run: |
          docker build -t hello-world-web-app:1.0 -f -Continuous-Integration-Continuous-Deployment-CI-CD-Pipeline/Dockerfile .
          docker images  # Display a list of Docker images for verification

  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.troyranger }}
          DOCKERHUB_TOKEN: ${{ secrets.dckr_pat_pvzASTd88DqN__jk87hH9MprqBw }}
        run: |
          echo "dckr_pat_pvzASTd88DqN__jk87hH9MprqBw" | docker login -u "troyranger" --password-stdin

      - name: Tag Docker Image
        run: |
          docker tag hello-world-web-app:1.0 troyranger/hello-world-web-app:1.0

      - name: Push Docker Image to Registry
        run: |
          docker push troyranger/hello-world-web-app:1.0

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Pull Docker Image for Testing
        run: |
          docker pull troyranger/hello-world-web-app:1.0

      - name: Start Docker Container for Testing
        run: |
          docker run -d -p 8080:80 --name hello-world-container troyranger/hello-world-web-app:1.0
          sleep 5  # Give the container some time to start

      - name: Run Tests (Example)
        run: |
          # Add your testing commands here.
          # For a "Hello, World!" app, you might not have extensive tests.
          # This is a placeholder for your specific testing requirements.

      - name: Stop Docker Container
        run: |
          docker stop hello-world-container
          docker rm hello-world-container
